[package]
name = "anomaly"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.5.4"
# rand = "0.8.5"
windows = "0.43.0"
pkg-config = "0.3.26"